# Welcome to Jekyll!
#

# Site settings
title: Shuwei Xu | suwi^.^
description: |
  Shuwei's 12-week recording  
  in [GSoC 2018](https://summerofcode.withgoogle.com/projects/#5284664500027392)  
owner: Shuwei Xu # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: cherub_cinderella@outlook.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://medium.com/suwi" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/<username>
  github: https://github.com/cynthiasuwi
  linkedin-square: https://linkedin.com/in/cynthiasuwi
  facebook-official: https://facebook.com/cynthiasuwi
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
